# Generated by Django 4.1 on 2024-03-01 11:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FishInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('movie', models.FileField(upload_to='upload_video/')),
                ('info', models.TextField(max_length=1000)),
                ('gender', models.IntegerField(null=True)),
                ('fish_mixed', models.CharField(max_length=200)),
                ('temp', models.IntegerField(null=True)),
                ('fish_size', models.IntegerField(null=True)),
                ('aquarium_size', models.IntegerField(null=True)),
                ('material', models.CharField(max_length=200)),
                ('food', models.CharField(max_length=200)),
                ('create_at', models.DateTimeField(default=datetime.datetime.now)),
                ('update_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_file_name', models.ImageField(upload_to='icon_img/')),
                ('icon_name', models.CharField(max_length=50)),
                ('create_at', models.DateTimeField(default=datetime.datetime.now)),
                ('update_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('mail', models.EmailField(db_index=True, max_length=254)),
                ('password', models.CharField(max_length=128)),
                ('create_at', models.DateTimeField(default=datetime.datetime.now)),
                ('update_at', models.DateTimeField(default=datetime.datetime.now)),
                ('icon_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='net_a_db.icon')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(default=datetime.datetime.now)),
                ('update_at', models.DateTimeField(default=datetime.datetime.now)),
                ('fish_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='net_a_db.fishinfo')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='net_a_db.user')),
            ],
        ),
        migrations.CreateModel(
            name='FishPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish_file_name', models.ImageField(upload_to='upload_img/')),
                ('display_number', models.IntegerField()),
                ('create_at', models.DateTimeField(default=datetime.datetime.now)),
                ('update_at', models.DateTimeField(default=datetime.datetime.now)),
                ('fish_info_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='net_a_db.fishinfo')),
            ],
        ),
        migrations.AddField(
            model_name='fishinfo',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='net_a_db.user'),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(default=datetime.datetime.now)),
                ('update_at', models.DateTimeField(default=datetime.datetime.now)),
                ('fish_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='net_a_db.fishinfo')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='net_a_db.user')),
            ],
        ),
    ]
