# Generated by Django 4.1 on 2024-03-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net_a_db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='icon',
            name='fish_mixed',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
