# Generated by Django 4.1 on 2024-03-03 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('net_a_db', '0002_icon_fish_mixed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icon',
            name='fish_mixed',
        ),
        migrations.AddField(
            model_name='icon',
            name='icon_text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='fishinfo',
            name='aquarium_size',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='fishinfo',
            name='fish_size',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='fishinfo',
            name='gender',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='fishinfo',
            name='temp',
            field=models.IntegerField(blank=True),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(blank=True)),
                ('picture', models.FileField(blank=True, upload_to='user/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
