# Generated by Django 4.1 on 2024-03-06 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('net_a_db', '0003_remove_icon_fish_mixed_icon_icon_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='icon',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='net_a_db.icon'),
        ),
    ]
